# This will run on Travis' 'new' container-based infrastructure
sudo: false

os: osx
osx_image: xcode 10.1
language: c++

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: CppStep
    - GH_REPO_REF: github.com/CppStep/CppStep.git

# Install dependencies
addons:
  homebrew:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x genDocs.sh
  - ./genDocs.sh
